### PR TITLE
Add distance mathod to Coordinates. Add tests. Small Fixes.

### LINKED ISSUE #56: transformation of Coordinate class
add: 
1.c-tor with 2 parameters (x-pos, y-pos)
2. operator == 
3. static function distance()
'static size_t distance(const Coordinates & lhs, const Coordinates & rhs)'
this function should return the distance between two coordinates.

### PR DESCRIPTION
**Pull request by runer53248**

### CODE REVIEW

File: shm/Island.hpp [hunk 1]
```diff
@@ -11,20 +11,21 @@ class Island {
 
     class Coordinates {
     public:
+        static constexpr size_t distance(const Coordinates& lhs, const Coordinates& rhs) {
+            auto pairX = std::minmax(lhs.positionX_, rhs.positionX_);
+            auto pairY = std::minmax(lhs.positionY_, rhs.positionY_);
```
Comment (Martyna-Tu) [inline shm/Island.hpp:16]: std::minmax -> it is really necessary ? In my opinion, equation below will be fine without minmax - we can just square a negative number .

Comment (runer53248) [reply shm/Island.hpp:16]: size_t dont have negative number.
